# Generated by Django 3.1.4 on 2021-01-09 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('gstin', models.CharField(default=0, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('remarks', models.CharField(default=' ', max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.firm')),
            ],
        ),
    ]
