# Generated by Django 3.1 on 2021-01-18 14:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('firm_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('date', models.DateField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('size', models.CharField(choices=[('1.0', '1.0'), ('1.5', '1.5'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('4.0', '4.0'), ('5.0', '5.0'), ('6.0', '6.0')], max_length=3)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity', models.IntegerField(default=0)),
                ('making_type', models.CharField(choices=[('Framed', 'Framed'), ('Sticked', 'Sticked')], max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=100)),
                ('firm_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.firm')),
            ],
        ),
    ]
