# Generated by Django 3.1.4 on 2021-01-09 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='firm',
            name='gstin',
            field=models.CharField(default='', max_length=15),
        ),
    ]
