# Generated by Django 3.1 on 2021-01-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firm',
            options={'ordering': ['firm_name']},
        ),
    ]
