# Generated by Django 3.1.4 on 2021-01-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20210109_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='remarks',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='firm',
            name='gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
