# Generated by Django 3.1.4 on 2021-01-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20210109_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='making_type',
            field=models.CharField(choices=[('F', 'Framed'), ('S', 'Sticked')], default='Framed', max_length=10),
        ),
    ]
