# Generated by Django 3.1.4 on 2021-01-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_auto_20210109_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='name',
            new_name='firm_name',
        ),
        migrations.RenameField(
            model_name='firm',
            old_name='name',
            new_name='firm_name',
        ),
    ]
