# Generated by Django 3.1.4 on 2021-01-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_auto_20210109_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
