# Generated by Django 3.1.4 on 2021-01-09 18:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_auto_20210109_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 9, 18, 1, 50, 549417, tzinfo=utc)),
        ),
    ]
