# Generated by Django 3.1.4 on 2021-01-09 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_firm_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 9, 18, 2, 8, 24705, tzinfo=utc)),
        ),
    ]
